---
- name: "install webapp v5"
  become: yes
  hosts: prod
  tags: webapp_v5
  vars:
    ansible_python_interpreter: /usr/bin/python3
    src: templates/index.html.j2
    image: nginx
    container: nginx-server
    port: 8080
    repogit: https://github.com/diranetafen/static-website-example.git
  vars_files:
    - files/secrets/credentials.yaml
  tasks:
    - name: "set up front"
      import_role: 
        name: front
